name: ci

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1
      - name: build
        run: msbuild src/FormulaInterpreter.App.VisualBasic/FormulaInterpreter.App.VisualBasic.vbproj /t:Restore /t:Build /p:Configuration=Release
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: src/FormulaInterpreter.App.VisualBasic/bin/Release
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy to GitHub Releases
    needs: [ build ]
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: prepare
        run: |
          mkdir -p staging/KursB_EsslingerSimon/source
          cp -r src/FormulaInterpreter.App.VisualBasic staging/KursB_EsslingerSimon/source/
          cp -r src/FormulaInterpreter.Logic.VisualBasic staging/KursB_EsslingerSimon/source/
          cp -r src/FormulaInterpreter.Logic.VisualBasic.Test staging/KursB_EsslingerSimon/source/
          mkdir -p staging/KursB_EsslingerSimon/bin
          mv artifacts/build/* staging/KursB_EsslingerSimon/bin
          cd staging && zip -r ../KursB_EsslingerSimon.zip KursB_EsslingerSimon
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: KursB_EsslingerSimon.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
