name: ci

on:
  push:
    paths:
      - 'src/**'
      - '!src/.devcontainer/**'
      - '!src/.vscode/**'
      - '!src/.vs/**'
      - '!src/.gitignore'
  pull_request:
    paths:
      - 'src/**'
      - '!src/.devcontainer/**'
      - '!src/.vscode/**'
      - '!src/.vs/**'
      - '!src/.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup nuget
        uses: nuget/setup-nuget@v1
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1
      - name: install dependencies
        run: nuget restore src/FormulaInterpreter.App.VisualBasic/FormulaInterpreter.App.VisualBasic.vbproj
      - name: build
        run: msbuild src/FormulaInterpreter.App.VisualBasic/FormulaInterpreter.App.VisualBasic.vbproj /t:Build /p:Configuration=Release
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: src/FormulaInterpreter.App.VisualBasic/bin/Release
